# Generated by Django 3.2.16 on 2023-03-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shopuser',
            table='auth_user',
        ),
    ]
