# Generated by Django 3.2.16 on 2023-03-22 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20230322_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='unsuccesful_login',
            new_name='login_attempts',
        ),
    ]
