# Generated by Django 3.2.16 on 2023-03-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_shopuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shopuser',
            managers=[
            ],
        ),
    ]
