# Generated by Django 3.2.16 on 2023-03-21 21:29

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_shopuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shopuser',
            managers=[
                ('objects', users.managers.ShopUserManager()),
            ],
        ),
    ]
