# Generated by Django 3.2.16 on 2023-03-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_unsuccesful_login_shopuser_login_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='datetime_blocked',
        ),
    ]
