# Generated by Django 3.2.16 on 2023-03-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_price'),
        ('users', '0005_remove_shopuser_datetime_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='items',
            field=models.ManyToManyField(help_text='Товары в корзине пользователя', related_name='users', to='catalog.Item', verbose_name='товары'),
        ),
    ]
