# Generated by Django 3.2.16 on 2023-03-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст письма', verbose_name='текст')),
                ('cretated_on', models.DateTimeField(auto_now=True, help_text='Когда отправили фидбек', verbose_name='дата и время создания')),
                ('email', models.EmailField(help_text='Электронная почта получателя', max_length=254, verbose_name='электронная почта')),
            ],
            options={
                'verbose_name': 'фидбек',
                'verbose_name_plural': 'фидбеки',
            },
        ),
    ]
