# Generated by Django 3.2.16 on 2023-03-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('A', 'получено'), ('B', 'в обработке'), ('C', 'ответ дан')], default='A', help_text='Статус обработки формы', max_length=100, verbose_name='статус'),
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback_feedback',
        ),
    ]
