# Generated by Django 3.2.16 on 2023-03-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20230313_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('получено', 'получено'), ('в обработке', 'в обработке'), ('ответ дан', 'ответ дан')], default='получено', help_text='Статус обработки формы', max_length=100, verbose_name='статус'),
        ),
    ]
