# Generated by Django 3.2.16 on 2023-03-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20230324_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='cretated_on',
            new_name='created_on',
        ),
    ]
