# Generated by Django 3.2.16 on 2023-03-15 04:45

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Электронная почта получателя', max_length=254, verbose_name='электронная почта')),
            ],
            options={
                'verbose_name': 'данные пользователя',
                'db_table': 'feedback_feedbackuserdata',
            },
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.CreateModel(
            name='FeedbackFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Загрузите файл', upload_to=feedback.models.generate_file_path, verbose_name='файл')),
                ('feedback', models.ForeignKey(help_text='Фидбек, к которому привязан файл', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='feedback.feedback', verbose_name='фидбек')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default=1, help_text='Пользователь, к которому привязан фидбек', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.feedbackuserdata', verbose_name='пользователь'),
            preserve_default=False,
        ),
    ]
