# Generated by Django 3.2.16 on 2023-03-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20230315_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackfile',
            options={'verbose_name': 'файл фидбека', 'verbose_name_plural': 'файлы фидбека'},
        ),
        migrations.AlterModelTable(
            name='feedbackfile',
            table='feedback_feedbackfile',
        ),
    ]
