# Generated by Django 3.2.16 on 2023-03-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20230315_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='cretated_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Когда отправили фидбек', verbose_name='дата и время создания'),
        ),
    ]
