# Generated by Django 3.2.16 on 2023-03-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_feedback_cretated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(help_text='Введите текст фидбека', verbose_name='текст'),
        ),
    ]
