# Generated by Django 3.2.16 on 2023-03-26 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(help_text='товар, к которому относится рейтинг', on_delete=django.db.models.deletion.CASCADE, related_name='item_rating', to='catalog.item', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(help_text='пользователь, который оставил рейтинг', on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
