# Generated by Django 3.2.16 on 2023-03-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20230326_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, 'Ненависть'), (2, 'Неприязнь'), (3, 'Нейтрально'), (4, 'Обожание'), (5, 'Любовь')], default=5, help_text='Оцените товар', verbose_name='оценка'),
        ),
    ]
