# Generated by Django 3.2.16 on 2023-02-22 12:33

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован или нет', verbose_name='опубликован')),
                ('name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='имя')),
                ('slug', models.SlugField(help_text='Уникальное для каждого элемента поле', max_length=200, unique=True, verbose_name='уникальное поле')),
                ('keyword', models.CharField(editable=False, help_text='Нормализованное значение', max_length=150, unique=True, verbose_name='нормализованное значение')),
                ('weight', models.PositiveSmallIntegerField(default=100, help_text='Введите вес товара (положительное целое число от 1 до 32767)', validators=[django.core.validators.MaxValueValidator(32767), django.core.validators.MinValueValidator(1)], verbose_name='вес')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'catalog_category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован или нет', verbose_name='опубликован')),
                ('name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='имя')),
                ('slug', models.SlugField(help_text='Уникальное для каждого элемента поле', max_length=200, unique=True, verbose_name='уникальное поле')),
                ('keyword', models.CharField(editable=False, help_text='Нормализованное значение', max_length=150, unique=True, verbose_name='нормализованное значение')),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'тэги',
                'db_table': 'catalog_tag',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован или нет', verbose_name='опубликован')),
                ('name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='имя')),
                ('text', models.TextField(help_text='Введите описание', validators=[catalog.validators.ValidateMustContain('превосходно', 'роскошно')], verbose_name='описание')),
                ('category', models.ForeignKey(help_text='Категория, к которой принадлежит товар', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='catalog.category', verbose_name='категория')),
                ('tags', models.ManyToManyField(help_text='Тэги товара', related_name='catalog_items', to='catalog.Tag', verbose_name='тэги')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'db_table': 'catalog_item',
            },
        ),
    ]
