# Generated by Django 3.2.16 on 2023-02-19 12:15

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован или нет', verbose_name='Опубликован')),
                ('name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='Имя')),
                ('slug', models.CharField(help_text='Уникальное для каждого элемента поле', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Уникальное поле')),
                ('weight', models.PositiveSmallIntegerField(default=100, help_text='Введите вес товара (положительное целое число от 0 до 32767)', validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'catalog_category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован или нет', verbose_name='Опубликован')),
                ('name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='Имя')),
                ('slug', models.CharField(help_text='Уникальное для каждого элемента поле', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Уникальное поле')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'db_table': 'catalog_tag',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован или нет', verbose_name='Опубликован')),
                ('name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='Имя')),
                ('text', models.TextField(help_text='Введите описание', verbose_name='Описание')),
                ('category', models.ForeignKey(help_text='Категория, к которой принадлежит товар', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='catalog.category')),
                ('tags', models.ManyToManyField(help_text='Тэги товара', related_name='catalog_items', to='catalog.Tag')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'catalog_item',
            },
        ),
    ]
