# Generated by Django 3.2.16 on 2023-03-20 14:11

import catalog.validators
import ckeditor.fields
import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован или нет', verbose_name='опубликован')),
                ('name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='имя')),
                ('slug', models.SlugField(help_text='Уникальное для каждого элемента поле', max_length=200, unique=True, verbose_name='уникальное поле')),
                ('keyword', models.CharField(editable=False, max_length=150)),
                ('weight', models.PositiveSmallIntegerField(default=100, help_text='Введите вес товара (положительное целое число от 1 до 32767)', validators=[django.core.validators.MaxValueValidator(32767), django.core.validators.MinValueValidator(1)], verbose_name='вес')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'catalog_category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован или нет', verbose_name='опубликован')),
                ('name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='имя')),
                ('slug', models.SlugField(help_text='Уникальное для каждого элемента поле', max_length=200, unique=True, verbose_name='уникальное поле')),
                ('keyword', models.CharField(editable=False, max_length=150)),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'тэги',
                'db_table': 'catalog_tag',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликован или нет', verbose_name='опубликован')),
                ('name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='имя')),
                ('text', ckeditor.fields.RichTextField(help_text='Введите описание', validators=[catalog.validators.ValidateMustContain('превосходно', 'роскошно')], verbose_name='описание')),
                ('is_on_main', models.BooleanField(default=False, help_text='Отображать ли товар на главной странице', verbose_name='на главной')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Дата создания товара', verbose_name='дата создания')),
                ('updated_at', models.DateField(auto_now=True, help_text='Дата изменения товара', verbose_name='дата изменения')),
                ('category', models.ForeignKey(help_text='Категория, к которой принадлежит товар', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='catalog.category', verbose_name='категория')),
                ('tags', models.ManyToManyField(help_text='Тэги товара', related_name='catalog_items', to='catalog.Tag', verbose_name='тэги')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'db_table': 'catalog_item',
            },
        ),
        migrations.CreateModel(
            name='ImageToItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите картинку', upload_to=core.models.generate_image_path, verbose_name='картинка')),
                ('item', models.OneToOneField(help_text='Главное изображение для товара', on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='catalog.item', verbose_name='превью')),
            ],
            options={
                'verbose_name': 'главное изображение',
                'verbose_name_plural': 'главные изображения',
                'db_table': 'catalog_image',
            },
        ),
        migrations.CreateModel(
            name='GaleryToItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите картинку', upload_to=core.models.generate_image_path, verbose_name='картинка')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galery', to='catalog.item', verbose_name='галерея')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'галерея изображений',
                'db_table': 'catalog_galery',
            },
        ),
    ]
