# Generated by Django 3.2.16 on 2023-03-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(default=1000, help_text='Цена товара', verbose_name='цена'),
        ),
    ]
