# Generated by Django 3.2.16 on 2023-02-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='keyword',
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='tag',
            name='keyword',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
