# Generated by Django 3.2.16 on 2023-02-28 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_imagetoitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerytoitem',
            name='image',
            field=models.ImageField(help_text='Загрузите картинку', upload_to='catalog/', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='galerytoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galery', to='catalog.item', verbose_name='галерея'),
        ),
        migrations.AlterField(
            model_name='imagetoitem',
            name='image',
            field=models.ImageField(help_text='Загрузите картинку', upload_to='catalog/', verbose_name='картинка'),
        ),
    ]
