# Generated by Django 3.2.16 on 2023-02-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Категория, к которой принадлежит товар', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(help_text='Тэги товара', related_name='catalog_items', to='catalog.Tag', verbose_name='Тэги'),
        ),
    ]
