# Generated by Django 3.2.16 on 2023-02-21 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20230219_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.PositiveSmallIntegerField(default=100, help_text='Введите вес товара (положительное целое число от 0 до 32767)', validators=[django.core.validators.MaxValueValidator(32767), django.core.validators.MinValueValidator(0)], verbose_name='Вес'),
        ),
    ]
