# Generated by Django 3.2.16 on 2023-03-04 18:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, help_text='Отображать ли товар на главной странице', verbose_name='на главной'),
        ),
        migrations.AlterField(
            model_name='galerytoitem',
            name='image',
            field=models.ImageField(help_text='Загрузите картинку', upload_to=core.models.generate_image_path, verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='imagetoitem',
            name='image',
            field=models.ImageField(help_text='Загрузите картинку', upload_to=core.models.generate_image_path, verbose_name='картинка'),
        ),
    ]
