# Generated by Django 3.2.16 on 2023-03-07 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20230304_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 3, 7), help_text='Дата создания товара', verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateField(default=datetime.date(2023, 3, 7), help_text='Дата изменения товара', verbose_name='дата изменения'),
        ),
    ]
