# Generated by Django 3.2.16 on 2023-03-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20230307_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Дата создания товара', verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateField(auto_now=True, help_text='Дата изменения товара', verbose_name='дата изменения'),
        ),
    ]
