# Generated by Django 3.2.16 on 2023-03-31 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_item_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(help_text='Товар из корзины пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='catalog.item', verbose_name='товар')),
                ('user', models.ForeignKey(help_text='Пользователь, добавивщий товар в корзину', on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
                'db_table': 'basket_basket',
            },
        ),
    ]
